services:
  workflow-manager:
    build: 
      context: .
      dockerfile: Dockerfile.manager
    container_name: workflow-manager
    restart: unless-stopped
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - LOG_LEVEL=INFO
      - WORKER_IMAGE=workflow-worker:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${PWD}/tmp:/tmp
    networks:
      - workflow-net

  workflow-worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    image: workflow-worker:latest
    networks:
      - workflow-net

networks:
  workflow-net:
    name: workflow-net
    driver: bridge